name: followBranch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Checkout
      - uses: actions/checkout@master
      - name: git setting
        run: |
          git config --local user.email "hirakue388@hoge.com"
          git config --local user.name "hirakue388"