name: followBranch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: git setting
        run: |
          git config --local user.email "hirakue388@hoge.com"
          git config --local user.name "hirakue388"
      - name: checkout-follow-branch
        run: git checkout -b follow_1
      - name: push follow_1 branch
        run: git push -f origin follow_1
        